version: '3.4'
services:
  redis:
    image: 'redis:latest'
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      rede_local:

  dock:
    container_name: dock-transfer-banking
    build: .
    restart: always
    environment:
      - SPRING_PROFILE=docker
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      redis:
        condition: service_started
    networks:
      rede_local:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=petshop-dock
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=dock
    volumes:
      - /tmp/postgres-volume:/data/db
      - ./configuration/db/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      rede_local:

networks:
  rede_local: