spring:
  application:
    name: dock
  web:
    resources:
      add-mappings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      enabled-by-default: true

server:
  port: 8080
  servlet:
    context-path: /dock
    encoding:
      charset: UTF-8
      enabled: true
  max-http-request-header-size: 48000

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/dock
    username: dock
    password: test1234
    driverClassName: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      platform: postgres

redis:
  host: localhost
  port: 6379

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/dock
    username: dock
    password: test1234
    driverClassName: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      platform: postgres

redis:
  host: redis
  port: 6379